parser: babel-eslint

parserOptions:
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jsx-a11y/recommended
  - prettier

plugins:
  - react-hooks

rules:
  no-console: 0
  react/prop-types: 0
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
